name=Register
version=1.0.1
author=PouwerTronics
maintainer=Lorenzo Pouw <info@pouwertronics.nl>
sentence=Arduino library for storing and reading registers in EEPROM with CRC8 integrity.
paragraph=Arduino library for efficient and reliable storage of variables and structs in EEPROM using CRC8 for data integrity. Supports easy allocation and access of persistent variables.
category=Memory
url=https://pouwertronics.nl
architectures=*
includes=Register.h
