name=DigitalInput
version=1.1.0
author=PouwerTronics
maintainer=Lorenzo Pouw <info@pouwertronics.nl>
sentence=Arduino library for debounced and robust digital input handling with edge detection and active duration.
paragraph=Arduino library for robust, debounced digital input with edge detection, invert logic, active duration measurement, and millis() overflow protection. Supports pull-up and configurable debounce time.
category=Signal Input/Output
url=https://pouwertronics.nl
architectures=*
includes=DigitalInput.h
